fido_RP/myblog/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'myblog.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^index/', 'articles.views.getMainPage'),
    url(r'^logout/', 'articles.views.userLogout'),
    url(r'^regist/', 'articles.views.userRegister'),
    url(r'^addarticle/', 'articles.views.addArticle'),
    url(r'^article/', 'articles.views.showArticle'),
    url(r'^userinfo/', 'articles.views.getUser'),
    url(r'^delcomment/', 'articles.views.delComment'),
    url(r'^delarticle/', 'articles.views.delArticle'),
    url(r'^support/', 'articles.views.showSupport'),
    url(r'^editarticle/', 'articles.views.editActicle'),
    url(r'^facetid/', 'articles.views.getFaceIdList'),
    url(r'^trustedapps', 'articles.views.getTrustedApps'),
    url(r'^bind', 'articles.views.bindUsers'),
    url(r'^authenticate', 'articles.views.getAuthenticated'),
    url(r'^response', 'articles.views.uploadResponse'),
    url(r'^admin/', include(admin.site.urls)),
)

fido_RP/articles/models.py
#!/usr/bin/python  
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

class BaseCategory(models.Model):
    id = models.AutoField(primary_key = True)
    base_name = models.CharField(max_length = 20, verbose_name = "类名")
    description = models.CharField(max_length = 100, verbose_name = "描述")
    class Meta:
        verbose_name_plural = '分类管理'
        verbose_name = '分类'
    def __unicode__(self):
        return self.base_name

class Tag(models.Model):
    id = models.AutoField(primary_key = True)
    tag_name = models.CharField(max_length = 20, verbose_name = "标签名")
    category = models.IntegerField(verbose_name = "所属分类")

class Essay(models.Model):
    id = models.AutoField(primary_key = True)
    userId = models.IntegerField(max_length=30, verbose_name="用户Id")
    username = models.CharField(max_length=40, verbose_name="用户名")
    subject = models.CharField(max_length = 50, verbose_name = "题目")
    type = models.BooleanField(default=True, verbose_name = "是否原创")
    category = models.ForeignKey(BaseCategory, verbose_name = "分类")
    content = models.TextField(verbose_name = "文章内容")
    modification_date = models.DateField(verbose_name = "修改时间")
    publish_date = models.DateField(verbose_name = "发布时间")
    essay_status = models.CharField(max_length = 10, verbose_name = "文章状态")
    class Meta:
        verbose_name_plural = '文章管理'
        verbose_name = '文章'
    def __unicode__(self):
        return self.subject

class Comment(models.Model):
    id = models.AutoField(primary_key = True)
    essay = models.ForeignKey(Essay, verbose_name = "所属文章")
    publisher = models.ForeignKey(User, verbose_name = "评论人")
    support_num = models.IntegerField(verbose_name = "赞")
    tend = models.IntegerField(verbose_name = "态度")
    content = models.TextField(verbose_name = "评论内容")
    publish_time = models.DateTimeField(verbose_name = "发布时间")
    class Meta:
        verbose_name_plural = '评论管理'
        verbose_name = '评论'
    def __unicode__(self):
        title = self.content
        if len(title) > 10:
            title = title[0 : 10] + '...'
        return title

class tagEssayRelation(models.Model):
    essayId = models.ForeignKey(Essay, verbose_name = "文章ID")
    tagId = models.ForeignKey(Tag, verbose_name = "标签ID")

class supportCommentRelation(models.Model):
    commentId = models.ForeignKey(Comment, verbose_name = "评论Id")
    userId = models.ForeignKey(User, verbose_name = "用户Id")

class FacetIDs (models.Model):
    id = models.AutoField(primary_key=True)
    facetId = models.CharField(max_length=100, verbose_name="facetId")
    class Meta:
        verbose_name_plural = 'facetId管理'
        verbose_name = 'facetId'

fido_RP/forms/articleForms.py
#!/usr/bin/python  
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from articles.models import BaseCategory, Tag
import re

class LoginForm(forms.Form):
    username = forms.CharField(label = '用户名', max_length = 20)
    password = forms.CharField(label = '密码', max_length = 25, widget = forms.PasswordInput())

class ArticleForm(forms.Form):
    categories = BaseCategory.objects.all()
    subject = forms.CharField(label = '文章标题', max_length = 50)
    isOrigin = forms.BooleanField(label = '是否原创', required = False)
    category = forms.ModelChoiceField(label = '分类', queryset = categories)
    status = forms.ChoiceField(choices = [('public', '公开'), ('limited', '受限'), ('private', '私密')])
    tag = forms.CharField(label = '标签', max_length = 50)
    content = forms.CharField(label = '内容', widget=forms.Textarea(attrs={'class': 'textarea'}))

class CommentForm(forms.Form):
    content = forms.CharField(label = '评论内容', widget = forms.Textarea(attrs={'class': 'commentField'}))
    essayId = forms.IntegerField(label = '文章ID')
    publisher = forms.IntegerField(label = '发布者')
    tend = forms.ChoiceField(choices = [('1', '赞'), ('0', '可以接受'), ('-1', '倒')])

fido_RP/articles/views.py
#!/usr/bin/python  
# -*- coding: utf-8 -*-
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import authenticate, login, logout
from django.template import RequestContext
from django.http import HttpResponseRedirect, HttpResponse 
from forms.userForms import LoginForm, RegistForm
from forms.articleForms import ArticleForm, CommentForm
from django.contrib.auth.models import User, Group
from articles.models import Essay, Tag, tagEssayRelation, Comment, supportCommentRelation, FacetIDs
from django.core.exceptions import ObjectDoesNotExist
import time

import json
import requests

# Create your views here.
def getMainPage(request):
    fails = False
    if request.method == 'POST':
        loginform = LoginForm(request.POST)
        if loginform.is_valid():
            userData = loginform.cleaned_data
            user = authenticate(username = userData['username'], password = userData['password'])
            if user is not None:
                login(request, user)
                return HttpResponseRedirect('/index/')
            else:
                fails = True
                return render_to_response('login.html', locals(), context_instance = RequestContext(request))

    else:
        loginform = LoginForm()
    essays = Essay.objects.filter(essay_status__in = ['public', 'limited'])
    return render_to_response('index.html', locals(), context_instance = RequestContext(request))

# def userLogin(request):
#     fail = False
#     user = authenticate( username = request.POST['username'], password = request.POST['password'])
#     if user is not None:
#         login(request, user)
#         return HttpResponseRedirect('/index/')
#     else:
#         fail = True
#         return render_to_response('index.html', locals(), context_instance = RequestContext(request))

def userLogout(request):
    logout(request)
    return HttpResponseRedirect('/index/')

def userRegister(request):
    if request.method == "POST":
        regForm = RegistForm(request.POST)
        if regForm.is_valid():
            userInfo = regForm.cleaned_data
            user = User.objects.create_user(
                username = userInfo['username'],
                password = userInfo['password'],
                email = userInfo.get('email', 'noreply@example.com'),
                first_name = userInfo['first_name'],
                last_name = userInfo['last_name'],
                )
            newUser = authenticate( username = userInfo['username'], password = userInfo['password'])
            login(request, newUser)
            group = Group.objects.get(name = "normal user")
            group.user_set.add(user)
            return HttpResponseRedirect('/index/')
    else:
        regForm = RegistForm()
    return render_to_response('regist.html', locals(), context_instance = RequestContext(request))


def addComment(request):
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        print 'hello1'
        if commentForm.is_valid():
            print 'hello2'
            commentInfo = commentForm.cleaned_data
            print 'hello'
            print commentInfo['content']
            print commentInfo['essayId']
    
def editActicle(request):
    essayId = request.GET["essayId"]
    essay = Essay.objects.filter(id = essayId)[0]
    isEdit = essayId
    tagSet = tagEssayRelation.objects.filter(essayId = essay)
    tagStr = ""
    for tagRe in tagSet:
        tag = tagRe.tagId
        tagStr += tag.tag_name + ","
    tagStr = tagStr[ 0 : len(tagStr) - 1 ]
    articleForm = ArticleForm(
        initial = { 'subject' : essay.subject,
                    'content' : essay.content,
                    'isOrigin': essay.type,
                    'category':essay.category,
                    'status' : essay.essay_status,
                    'tag' : tagStr,
        }
    )
    isEdit = essayId
    return render_to_response('addArticle.html', locals(), context_instance = RequestContext(request))

def handleTag(tagStr, newEssay):
    tagEssayRelation.objects.filter(essayId = newEssay.id).delete()
    tag_id = 0
    final_tag = Tag()
    tagList = tagStr.split(',')
    for item in tagList:
        essay_tag = item.strip().lower()
        try:
            old_tag = Tag.objects.get(tag_name = essay_tag)
        except ObjectDoesNotExist:
            new_tag = Tag(
                tag_name = essay_tag,
                category = 0,
                )
            new_tag.save()
            final_tag = new_tag
        else:
            final_tag = old_tag
        tagessay_relation = tagEssayRelation(
            essayId = newEssay,
            tagId = final_tag,
            )
        tagessay_relation.save()


def addArticle(request):
    if request.method == "POST":
        articleForm = ArticleForm(request.POST)
        oldEssayId = int(request.GET.get('edit', '0'))
        userId = request.user.id
        username = request.user.username
        if articleForm.is_valid():
            articleInfo = articleForm.cleaned_data
            if oldEssayId == 0:
                newEssay = Essay(
                    subject = articleInfo['subject'],
                    type = articleInfo['isOrigin'],
                    category = articleInfo['category'],
                    content = articleInfo['content'],
                    modification_date = time.strftime('%Y-%m-%d',time.localtime(time.time())),
                    publish_date = time.strftime('%Y-%m-%d',time.localtime(time.time())),
                    essay_status = articleInfo['status'],
                    userId = userId,
                    username = username
                )
                newEssay.save()
                tagStr = articleInfo['tag']
                handleTag(tagStr, newEssay)
            else:
                newEssay = Essay.objects.filter(id = oldEssayId)[0]
                newEssay.subject = articleInfo['subject']
                newEssay.type = articleInfo['isOrigin']
                newEssay.category = articleInfo['category']
                newEssay.content = articleInfo['content']
                newEssay.modification_date = time.strftime('%Y-%m-%d',time.localtime(time.time()))
                newEssay.essay_status = articleInfo['status']
                newEssay.save()
                tagStr = articleInfo['tag']
                handleTag(tagStr, newEssay)
            return HttpResponseRedirect('/index/')
    else:
        articleForm = ArticleForm()
        isEdit = 0
    return render_to_response('addArticle.html', locals(), context_instance = RequestContext(request))

def showArticle(request):
    isSupported = []
    if request.method == "POST":
        commentForm = CommentForm(request.POST)
        if commentForm.is_valid():
            commentInfo = commentForm.cleaned_data
            user = User.objects.filter(id = commentInfo["publisher"])[0]
            essay = Essay.objects.filter(id = commentInfo["essayId"])[0]
            comment = Comment(
                essay = essay,
                publisher = user,
                tend = commentInfo["tend"],
                content = commentInfo["content"],
                publish_time = time.strftime('%Y-%m-%d %H:%M:%S',time.localtime(time.time())),
                support_num = 0,
                )
            comment.save()
            return HttpResponseRedirect('/article/?id=' + str(commentInfo["essayId"]))
    else:
        essay = Essay.objects.filter(id = request.GET.get('id'))[0]
        comments = Comment.objects.filter(essay = request.GET.get('id'))
        for comment in comments:
            if len(supportCommentRelation.objects.filter(userId = request.GET.get('uid', 0), commentId = comment.id)) != 0:
                comment.isSupported = True
            else:
                comment.isSupported = False
        commentForm = CommentForm()
    return render_to_response('article.html', locals(), context_instance = RequestContext(request))

def getUser(request):
    userInfo = User.objects.filter(id = request.GET.get('userId'))[0]
    return render_to_response('userInfo.html', locals(),context_instance = RequestContext(request))

def getFaceIdList(request):
    facetIds = FacetIDs.objects.all()
    loginform = LoginForm()
    return render_to_response('facetId.html', locals(),context_instance = RequestContext(request))

def delComment(request):
    Comment.objects.filter(id = request.GET.get('commentId')).delete()
    return HttpResponseRedirect('/article/?id=' + request.GET.get('essayId'))

def delArticle(request):
    Essay.objects.filter(id = request.GET.get('essayId')).delete()
    return HttpResponseRedirect('/index/')

def showSupport(request):
    commentId = request.GET['commentId']
    userId = request.GET['userId']
    commentSet = Comment.objects.filter(id = commentId)
    supportNum = commentSet[0].support_num
    relationSet = supportCommentRelation.objects.filter(commentId = commentId, userId = userId)
    relationExist = len(relationSet)
    if relationExist != 0 :
        supportNum -= 1
        relationSet.delete()
        commentSet.update(support_num = supportNum)
    else :
        supportNum += 1
        commentSet.update(support_num = supportNum)
        relation = supportCommentRelation(
                commentId = commentSet[0],
                userId = User.objects.filter(id = userId)[0],
            )
        relation.save()
    return HttpResponse(supportNum)

def getTrustedApps(request):
    facetIds = FacetIDs.objects.all()
    version = {
        "mj" : 1,
        "mn" : 0,
    }
    facetIdList = []
    for x in facetIds:
        facetIdList.append(x.facetId)
    TrustedApps = {
        "version" : version,
        "ids"     : facetIdList,
    }
    return HttpResponse(json.dumps(TrustedApps), content_type = "vnd.fi- do.trusted-apps+json")

@csrf_exempt
def bindUsers(request):
    if request.method == "POST":
        username = request.POST.get('username')

fido_RP/templates/addArticle.html
{% extends "base/base.html" %}
{% block morecss %}
{% load staticfiles %}
	<link href="{% static "bootstrap/css/signin.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/prettify.css" %}" rel="stylesheet">
    <link href="{% static "bootstrap/css/bootstrap-wysihtml5.css" %}" rel="stylesheet">
    <style type="text/css" media="screen">
	.btn.jumbo {
		font-size: 20px;
		font-weight: normal;
		padding: 14px 24px;
		margin-right: 10px;
		-webkit-border-radius: 6px;
		-moz-border-radius: 6px;
		border-radius: 6px;
	}

    .textarea{
        width: 810px;
        height: 200px;
    }

    .ibtn{
        margin:10px 60px 15px 200px;
    }
</style>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30181385-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
{% endblock %}
{% block header %}
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
  <div class="container location-center">
  <h2 class="form-signin-heading">编辑文章</h2>
      <br/>
      {% if isEdit %}
          <form action = "/addarticle/?edit={{isEdit}}" method = "post">
      {% else %}
          <form action = "/addarticle/" method = "post">
      {% endif %}
    {% csrf_token %}
        <div>
            {{articleForm.subject.errors}}
            <label>题目：</label>
             {{articleForm.subject}}
        </div>
        <br/>
        <div>
            {{articleForm.isOrigin.errors}}
            <label>是否原创：</label>
            {{articleForm.isOrigin}}
        </div>
        <br/>
        <div>
            {{articleForm.category.errors}}
            <label>分类：</label>
            {{articleForm.category}}
        </div>
        <br/>
        <div>
            {{articleForm.status.errors}}
            <label>文章显示：</label>
            {{articleForm.status}}
        </div>
        <br/>
        <div>
            {{articleForm.tag.errors}}
            <label>标签：</label>
            {{articleForm.tag}}    多个标签请用半角逗号隔开
        </div>
        <div  class="hero-unit" style="margin-top:40px">
            {{articleForm.content.errors}}
            <label>内容：</label>
            {{articleForm.content}}
        </div>
        <br/>
        {% if perms.articles.add_essay %}
        <input type = "submit" class="ibtn btn btn-success" value="发布">
        {% else %}
        <input type = "submit" class="ibtn btn btn-success" disabled="disabled" value="发布">
        {% endif %}
        <input type = "reset" class="ibtn btn btn-info" value="清空">
    </form>
  </div>

{% endblock %}

{% block js %}
    <script src="/static/bootstrap/js/wysihtml5-0.3.0.js"></script>
    <script src="/static/bootstrap/js/prettify.js"></script>
    <script src="/static/bootstrap/js/bootstrap-wysihtml5.js"></script>

    <script>
        $('.textarea').wysihtml5();
    </script>

    <script type="text/javascript" charset="utf-8">
        $(prettyPrint);
    </script>
{% endblock %}

fido_RP/templates/article.html
{% extends "base/base.html" %}
{% block header %}{% endblock %}
{% block content %}
    <div class="leave-top">
<h6 class="blog-post-title" style="text-align: center">{{essay.subject}}</h6>
    <br/>
    {% autoescape off %}
    {% ifequal essay.type 1 %}
        <p class="blog-post-meta" style="text-align: center">作者：{{ essay.username }}&nbsp;&nbsp;&nbsp;&nbsp;类型：原创</p>
    {% else %}
        <p class="blog-post-meta" style="text-align: center">作者：{{ essay.username }}&nbsp;&nbsp;&nbsp;&nbsp;类型：转载</p>
    {% endifequal %}
<div class="blog-main" >{{essay.content}}</div>
    {% endautoescape %}
{% if perms.articles.change_essay or request.user.id == essay.userId %}
<button class="btn btn-warning" onclick = "location.href='/editarticle/?essayId={{essay.id}}'" style="float: right">修改文章</button>
{% endif %}
<br/><br/>
<h3>评&nbsp;&nbsp;&nbsp;&nbsp;论 <span class="label label-default">share!</span></h3>
<br/><br/>
{% for comment in comments %}
    <blockquote>
	    <p>{{comment.content}}</p>
        <small style="text-align: right"><a href="/userinfo/?userId={{comment.publisher.id}}">{{comment.publisher.username}}</a>
            <cite>&nbsp;&nbsp;&nbsp;{{comment.publish_time}}</cite>
{% if comment.isSupported %}
<a class = "btn" id = "{{comment.id}}" href="#">已赞({{comment.support_num}})</a>&nbsp;&nbsp;&nbsp;
{% else %}
<a class = "btn" id = "{{comment.id}}" href="#">赞({{comment.support_num}})</a>&nbsp;&nbsp;&nbsp;
{% endif %}
{% if perms.articles.delete_comment or comment.publisher.username == request.user.username %}
<a href = "/delcomment/?commentId={{comment.id}}&essayId={{comment.essay.id}}">删除</a>
{% endif %}
    </small>
</blockquote>
<br/>
{% empty %}
<div class="alert alert-success">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <strong>=_=悲剧~</strong>&nbsp;&nbsp;&nbsp;本文暂无评论，快来发表你的看法吧！
</div>
{% endfor %}
<h3>我&nbsp;的&nbsp;看&nbsp;法 <span class="label label-success">speak!</span></h3>
<br/>
{% if request.user.is_authenticated and perms.articles.add_comment and essay.essay_status == 'public' %}
<form action = "" method = "post">
{% csrf_token %}
	<div>
		{{commentForm.content.errors}}
		{{commentForm.content}}
	</div>
	<div>
    <input type = "hidden" name = "essayId" value = {{request.GET.id}} />
		<!-- {{commentForm.essayId|default_if_none:"(N/A)"}} -->
	</div>
    <div>
        <input type = "hidden" name = "publisher" value = {{request.user.id}}>
    </div>
    <br/>
    <div>
        {{commentForm.tend.errors}}
        <label>态度：</label>
        {{commentForm.tend}}
        <input type = "submit" class="ibtn btn btn-success" style="float: right" value="发布">
    </div>
</form>
    {% else %}
        {% if request.user.is_authenticated %}
            {% if essay.essay_status == 'limited' %}
                <div class="alert alert-info">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>抱歉！</strong>&nbsp;&nbsp;&nbsp;本文作者暂未开放评论！
                </div>
            {% else %}
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong>抱歉！</strong>&nbsp;&nbsp;&nbsp;您暂时未取得评论权限，请联系管理员！
                </div>
            {% endif %}
        {% else %}
            <div class="alert alert-warning">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>先让我们认识你！</strong>&nbsp;&nbsp;&nbsp;请首先登录，再进行评论！
            </div>
        {% endif %}
    {% endif %}
    </div>
{% endblock %}
{% block on_ready %}
    $('a.btn[id]').bind("click",function(){
            var commentId = $(this).attr("id");
            $.ajax({
                type:"get",
                url: "/support/",
                data:{
                    commentId : commentId,
                    userId : {{request.user.id}},
                    csrfmiddlewaretoken: '{{ csrf_token }}'
                },
                success:function(data){
                    if(($("#" + commentId).html()).indexOf("已") >= 0){
                        $("#" + commentId).html("赞(" + data + ")");
                    }
                    else{
                        $("#" + commentId).html("已赞(" + data + ")");
                    }
                }
            }
            );
        }
);
{% endblock %}

fido_RP/templates/facetId.html
{% extends "base/base.html" %}
{% block left-header %}
		  <ul class="nav navbar-nav">
            <li class="inactive"><a href="/index/">Home</a></li>
            {% if request.user.id %}
            <li class="inactive"><a href="/userinfo/?userId={{ request.user.id }}">UserInfo</a></li>
            <li class="inactive"><a href="/bind">绑定</a></li>
            {% endif %}
            <li class="active"><a href="/facetid/">FacetIDs</a></li>
          </ul>
        {% endblock %}
{% block content %}
    <h1 style="text-align:center">RP facetID 信息</h1>
    <div class="list-group">
   <a href="#" class="list-group-item active">
      <h4 class="list-group-item-heading" style="text-align:center">
         该RP的所有合法FaceIDs
      </h4>
   </a>
   {% for facetId in facetIds %}
   <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
         {{ forloop.counter }}：{{facetId.facetId}}
      </h4>
   </a>
   {% endfor %}
</div>
{% endblock %}

fido_RP/templates/index.html
{% extends "base/base.html" %}
{% block content %}
<div class="row">
    <div class="blog-main blog-list">
    {% for essay in essays %}
	<div class="blog-post">
    {% if request.user.is_authenticated %}
    <h6 class="blog-post-title"><a href = "/article/?id={{essay.id}}&uid={{request.user.id}}">{{essay.subject}}</a></h6>
    {% else %}
    <h6 class="blog-post-title"><a href = "/article/?id={{essay.id}}">{{essay.subject}}</a></h6>
    {% endif %}
	<p class="blog-post-meta">{{ essay.publish_date }} by <a href="/userinfo/?userId={{ essay.userId }}">{{ essay.username }}</a></p>
    {% if essay.content|length > 100 %}
	<blockquote>
    {% autoescape off %}
        <p>{{essay.content|slice:"150"}}...... <a href = "/article/?id={{essay.id}}&uid={{request.user.id}}">查看更多>></a></p>
    {% endautoescape %}
	</blockquote>
    {% else %}
        {% autoescape off %}
        <p>{{essay.content}}</p>
        {% endautoescape %}
    {% endif %}
    {% if perms.articles.delete_essay or request.user.id == essay.userId%}
   <!-- <a href = "/delarticle/?essayId={{essay.id}}">删除文章</a> -->
    <button class="btn btn-danger" onclick="location.href='/delarticle/?essayId={{essay.id}}'" style="float: right">删除文章</button></div>
    {% else %}
    </div>
    {% endif %}
    {% empty %}
    <h2 style="text-align:center">当前没有可浏览文章</h2>
        <br/>
    {% endfor %}
	</div>
</div>
{% endblock %}

fido_RP/templates/regist.html
{% extends "base/base.html" %}
{% block morecss %} 
{% load staticfiles %}
<link href="{% static "bootstrap/css/signin.css" %}" rel="stylesheet">
{% endblock %}
{% block header %}
{% endblock %}
{% block right-header %}
<div class="navbar-collapse collapse">
    <div class="navbar-right">
        <a class="navbar-brand">欢迎你加入本站！</a>
    </div><!--/.navbar-right -->
</div><!--/.navbar-collapse -->
{% endblock %}
{% block sidebar %}
{% endblock %}
{% block content %}
<div class="container leave-top">
<form action = "/regist/" method = "post" class="form-signin" role="form">
 <h2 class="form-signin-heading">欢迎光临本站</h2>
{% csrf_token %}
    <div>
        <label>用户名：</label>
        {{regForm.username}}
        {{regForm.username.errors}}
    </div>
    <div>
        <label>姓氏：</label>
        {{regForm.last_name}}
        {{regForm.last_name.errors}}
    </div>
    <div>
        <label>名字：</label>
        {{regForm.first_name}}
        {{regForm.first_name.errors}}
    </div>
    <div>
        <label>密码：</label>
        {{regForm.password}}
        {{regForm.password.errors}}
    </div>
    <div>

        <label>确认密码：</label>
        {{regForm.confirmPassword}}
        {{regForm.confirmPassword.errors}}
    </div>
    <div>
        <label>邮箱：</label>
        {{regForm.email}}
        {{regForm.email.errors}}
    </div>
	<br>
    <button class="btn btn-lg btn-primary btn-block" type="submit">注&nbsp;&nbsp;&nbsp;册</button>
</form>
</div>
{% endblock %}

fido_RP/templates/userInfo.html
{% extends "base/base.html" %}
{% block left-header %}
    <ul class="nav navbar-nav">
        <li class="inactive"><a href="/index/">Home</a></li>
        {% if request.user.id %}
            <li class="active"><a href="/userinfo/?userId={{ request.user.id }}">UserInfo</a></li>
            <li class="inactive"><a href="/bind">绑定</a></li>
        {% endif %}
        <li class="inactive"><a href="/authenticate">认证</a></li>
        <li class="inactive"><a href="/facetid/">FacetIDs</a></li>
    </ul>
{% endblock %}
{% block content %}
    <h1 style="text-align:center">用户信息</h1>
    <div class="list-group">
   <a href="#" class="list-group-item active">
      <h4 class="list-group-item-heading">
         用户基本信息
      </h4>
   </a>
   <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
         真实姓名：{{userInfo.last_name}} {{userInfo.first_name}}
      </h4>
      <p class="list-group-item-text">
         参加小站组织的线下活动时，尽量使用真实姓名
      </p>
   </a>
   <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
         用户昵称：{{userInfo.username}}
      </h4>
      <p class="list-group-item-text">
         用户线上评论或发表文章将显示用户昵称
      </p>
   </a>
    <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
         用户邮箱：{{userInfo.email}}
      </h4>
      <p class="list-group-item-text">
         网站通过用户邮箱对用户反映的信息进行反馈
      </p>
   </a>
</div>
<div class="list-group">
   <a href="#" class="list-group-item active">
      <h4 class="list-group-item-heading">
         用户登录和注册信息
      </h4>
   </a>
   <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
         上次登录时间：{{userInfo.last_login}}
      </h4>
      <p class="list-group-item-text">
         您上次登录小站的具体时间
      </p>
   </a>
   <a href="#" class="list-group-item">
      <h4 class="list-group-item-heading">
          加入时间：{{userInfo.date_joined}}
      </h4>
      <p class="list-group-item-text">
          您注册成为小站成员的具体时间
      </p>
   </a>
</div>

{% endblock %}